### ISSUE TITLE
Error load  basic 

### ISSUE THREAD

**Issue by sowe** [joeharris76/azkaban_examples#1]
Dear Joe Harris
Thanks for your samples are very helpful. But I'm try to use your samples (basic) but azkaban show me the next label " i cant "Installation Failed. Error found in upload. Cannot upload. basic 2nd command cannot find dependency basic 1st command".
Any idea?

**Comment by joeharris76** [comment]
OK, I tweaked the project a bit to make things (hopefully) simpler. I also added prepared '.zip' files that you can use. I've tested that these work.
